### ISSUE TITLE
Error in locating Geohashes

### ISSUE THREAD

**Issue by datastreamx-plc** [adrianulbona/cloc#5]
There are some errors in locating geohashes. eg. "u0u1u58qnt" gives [Belgium, France, Luxembourg] though its in "France" only

**Comment by adrianulbona** [comment]
A bit of context, the library is using length 5 geohashes and `u0u1u` seems to be in all three countries: 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/1519016/80482350-613f0680-8954-11ea-8ebe-ba8b3482f7ee.png">
